apiVersion: v1
kind: Service
metadata:
  name: <JOB_NAME>
  namespace: python
spec:
  selector:
    app: <JOB_NAME>
  type:  NodePort
  ports:
  - name: http
    port: 8000
    targetPort:  8000
    nodePort: <OUT_PORT>


